In [1]:
import pandas as pd
import json
import csv

In [2]:
base_globe = pd.read_csv("host_city.csv", sep=";")

In [3]:
base_globe

,City,Country,Season,Year,latitude,longitude
0,Athens,Greece,Summer,1896,37.983810,23.727539
1,Paris,France,Summer,1900,48.856613,2.352222
2,St. Louis,United States,Summer,1904,38.627003,-90.199402
3,London,United Kingdom,Summer,1908,51.507351,-0.127758
4,Stockholm,Sweden,Summer,1912,59.329323,18.068581
5,Antwerp,Belgium,Summer,1920,51.219448,4.402464
6,Chamonix,France,Winter,1924,45.925461,6.869810
7,Paris,France,Summer,1924,48.856613,2.352222
8,St. Moritz,Switzerland,Winter,1928,46.497060,9.838440
9,Amsterdam,Netherlands,Summer,1928,52.370216,4.895168
10,Lake Placid,United States,Winter,1932,27.293510,-81.360573
11,Los Angeles,United States,Summer,1932,34.052235,-118.243683
12,Garmisch-Partenkirchen,Nazi Germany,Winter,1936,47.492371,11.086110
13,Berlin,Nazi Germany,Summer,1936,52.520008,13.404954
14,St. Moritz,Switzerland,Winter,1948,46.497060,9.838440
15,London,United Kingdom,Summer,1948,51.507351,-0.127758
16,Oslo,Norway,Winter,1952,59.913868,10.752245
17,Helsinki,Finland,Summer,1952,60.169857,24.938379
18,Cortina d'Ampezzo,Italy,Winter,1956,46.537380,12.138920
19,Stockholm,Sweden,Summer,1956,59.329323,18.068581
20,Squaw Valley,United States,Winter,1960,36.725788,-119.235817
21,Rome,Italy,Summer,1960,41.902782,12.496365
22,Innsbruck,Austria,Winter,1964,47.262691,11.394700
23,Tokyo,Japan,Summer,1964,35.689487,139.691711
24,Grenoble,France,Winter,1968,45.194260,5.731670
25,Mexico City,Mexico,Summer,1968,19.432608,-99.133209
26,Sapporo,Japan,Winter,1972,43.062096,141.354370
27,Munich,West Germany,Summer,1972,48.135124,11.581981
28,Innsbruck,Austria,Winter,1976,47.262691,11.394700
29,Montreal,Canada,Summer,1976,45.501690,-73.567253
30,Lake Placid,United States,Winter,1980,27.293510,-81.360573
31,Moscow,Soviet Union,Summer,1980,55.755825,37.617298
32,Sarajevo,Yugoslavia,Winter,1984,43.856258,18.413076
33,Los Angeles,United States,Summer,1984,34.052235,-118.243683
34,Calgary,Canada,Winter,1988,51.048615,-114.070847
35,Seoul,South Korea,Summer,1988,37.566536,126.977966
36,Albertville,France,Winter,1992,34.267849,-86.208801
37,Barcelona,Spain,Summer,1992,41.385063,2.173404
38,Lillehammer,Norway,Winter,1994,61.115273,10.466231
39,Atlanta,United States,Summer,1996,33.748997,-84.387985
40,Nagano,Japan,Winter,1998,36.653450,138.186035
41,Sydney,Australia,Summer,2000,-33.868820,151.209290
42,Salt Lake City,United States,Winter,2002,40.760780,-111.891045
43,Athens,Greece,Summer,2004,37.983810,23.727539
44,Turin,Italy,Winter,2006,45.068371,7.683070
45,Beijing,China,Summer,2008,39.904202,116.407394
46,Vancouver,Canada,Winter,2010,49.282730,-123.120735
47,London,United Kingdom,Summer,2012,51.507351,-0.127758
48,Sochi,Russia,Winter,2014,43.602810,39.734154

In [4]:
base_globe.to_csv(r'host_city.csv', index=False)

In [5]:
base_globe

,City,Country,Season,Year,latitude,longitude
0,Athens,Greece,Summer,1896,37.983810,23.727539
1,Paris,France,Summer,1900,48.856613,2.352222
2,St. Louis,United States,Summer,1904,38.627003,-90.199402
3,London,United Kingdom,Summer,1908,51.507351,-0.127758
4,Stockholm,Sweden,Summer,1912,59.329323,18.068581
5,Antwerp,Belgium,Summer,1920,51.219448,4.402464
6,Chamonix,France,Winter,1924,45.925461,6.869810
7,Paris,France,Summer,1924,48.856613,2.352222
8,St. Moritz,Switzerland,Winter,1928,46.497060,9.838440
9,Amsterdam,Netherlands,Summer,1928,52.370216,4.895168
10,Lake Placid,United States,Winter,1932,27.293510,-81.360573
11,Los Angeles,United States,Summer,1932,34.052235,-118.243683
12,Garmisch-Partenkirchen,Nazi Germany,Winter,1936,47.492371,11.086110
13,Berlin,Nazi Germany,Summer,1936,52.520008,13.404954
14,St. Moritz,Switzerland,Winter,1948,46.497060,9.838440
15,London,United Kingdom,Summer,1948,51.507351,-0.127758
16,Oslo,Norway,Winter,1952,59.913868,10.752245
17,Helsinki,Finland,Summer,1952,60.169857,24.938379
18,Cortina d'Ampezzo,Italy,Winter,1956,46.537380,12.138920
19,Stockholm,Sweden,Summer,1956,59.329323,18.068581
20,Squaw Valley,United States,Winter,1960,36.725788,-119.235817
21,Rome,Italy,Summer,1960,41.902782,12.496365
22,Innsbruck,Austria,Winter,1964,47.262691,11.394700
23,Tokyo,Japan,Summer,1964,35.689487,139.691711
24,Grenoble,France,Winter,1968,45.194260,5.731670
25,Mexico City,Mexico,Summer,1968,19.432608,-99.133209
26,Sapporo,Japan,Winter,1972,43.062096,141.354370
27,Munich,West Germany,Summer,1972,48.135124,11.581981
28,Innsbruck,Austria,Winter,1976,47.262691,11.394700
29,Montreal,Canada,Summer,1976,45.501690,-73.567253
30,Lake Placid,United States,Winter,1980,27.293510,-81.360573
31,Moscow,Soviet Union,Summer,1980,55.755825,37.617298
32,Sarajevo,Yugoslavia,Winter,1984,43.856258,18.413076
33,Los Angeles,United States,Summer,1984,34.052235,-118.243683
34,Calgary,Canada,Winter,1988,51.048615,-114.070847
35,Seoul,South Korea,Summer,1988,37.566536,126.977966
36,Albertville,France,Winter,1992,34.267849,-86.208801
37,Barcelona,Spain,Summer,1992,41.385063,2.173404
38,Lillehammer,Norway,Winter,1994,61.115273,10.466231
39,Atlanta,United States,Summer,1996,33.748997,-84.387985
40,Nagano,Japan,Winter,1998,36.653450,138.186035
41,Sydney,Australia,Summer,2000,-33.868820,151.209290
42,Salt Lake City,United States,Winter,2002,40.760780,-111.891045
43,Athens,Greece,Summer,2004,37.983810,23.727539
44,Turin,Italy,Winter,2006,45.068371,7.683070
45,Beijing,China,Summer,2008,39.904202,116.407394
46,Vancouver,Canada,Winter,2010,49.282730,-123.120735
47,London,United Kingdom,Summer,2012,51.507351,-0.127758
48,Sochi,Russia,Winter,2014,43.602810,39.734154

In [6]:
base = pd.read_csv("host_city.csv")

In [7]:
base

,City,Country,Season,Year,latitude,longitude
0,Athens,Greece,Summer,1896,37.983810,23.727539
1,Paris,France,Summer,1900,48.856613,2.352222
2,St. Louis,United States,Summer,1904,38.627003,-90.199402
3,London,United Kingdom,Summer,1908,51.507351,-0.127758
4,Stockholm,Sweden,Summer,1912,59.329323,18.068581
5,Antwerp,Belgium,Summer,1920,51.219448,4.402464
6,Chamonix,France,Winter,1924,45.925461,6.869810
7,Paris,France,Summer,1924,48.856613,2.352222
8,St. Moritz,Switzerland,Winter,1928,46.497060,9.838440
9,Amsterdam,Netherlands,Summer,1928,52.370216,4.895168
10,Lake Placid,United States,Winter,1932,27.293510,-81.360573
11,Los Angeles,United States,Summer,1932,34.052235,-118.243683
12,Garmisch-Partenkirchen,Nazi Germany,Winter,1936,47.492371,11.086110
13,Berlin,Nazi Germany,Summer,1936,52.520008,13.404954
14,St. Moritz,Switzerland,Winter,1948,46.497060,9.838440
15,London,United Kingdom,Summer,1948,51.507351,-0.127758
16,Oslo,Norway,Winter,1952,59.913868,10.752245
17,Helsinki,Finland,Summer,1952,60.169857,24.938379
18,Cortina d'Ampezzo,Italy,Winter,1956,46.537380,12.138920
19,Stockholm,Sweden,Summer,1956,59.329323,18.068581
20,Squaw Valley,United States,Winter,1960,36.725788,-119.235817
21,Rome,Italy,Summer,1960,41.902782,12.496365
22,Innsbruck,Austria,Winter,1964,47.262691,11.394700
23,Tokyo,Japan,Summer,1964,35.689487,139.691711
24,Grenoble,France,Winter,1968,45.194260,5.731670
25,Mexico City,Mexico,Summer,1968,19.432608,-99.133209
26,Sapporo,Japan,Winter,1972,43.062096,141.354370
27,Munich,West Germany,Summer,1972,48.135124,11.581981
28,Innsbruck,Austria,Winter,1976,47.262691,11.394700
29,Montreal,Canada,Summer,1976,45.501690,-73.567253
30,Lake Placid,United States,Winter,1980,27.293510,-81.360573
31,Moscow,Soviet Union,Summer,1980,55.755825,37.617298
32,Sarajevo,Yugoslavia,Winter,1984,43.856258,18.413076
33,Los Angeles,United States,Summer,1984,34.052235,-118.243683
34,Calgary,Canada,Winter,1988,51.048615,-114.070847
35,Seoul,South Korea,Summer,1988,37.566536,126.977966
36,Albertville,France,Winter,1992,34.267849,-86.208801
37,Barcelona,Spain,Summer,1992,41.385063,2.173404
38,Lillehammer,Norway,Winter,1994,61.115273,10.466231
39,Atlanta,United States,Summer,1996,33.748997,-84.387985
40,Nagano,Japan,Winter,1998,36.653450,138.186035
41,Sydney,Australia,Summer,2000,-33.868820,151.209290
42,Salt Lake City,United States,Winter,2002,40.760780,-111.891045
43,Athens,Greece,Summer,2004,37.983810,23.727539
44,Turin,Italy,Winter,2006,45.068371,7.683070
45,Beijing,China,Summer,2008,39.904202,116.407394
46,Vancouver,Canada,Winter,2010,49.282730,-123.120735
47,London,United Kingdom,Summer,2012,51.507351,-0.127758
48,Sochi,Russia,Winter,2014,43.602810,39.734154

In [8]:
with open ("host_city.csv", "r") as f:
    reader = csv.reader(f)
    next(reader)
    data = []
    for row in reader:
        data.append({"city": row[0], "country": row[1], "season": row[2], "year": row[3], "latitude": row[4], "longitude": row[5]})

In [9]:
with open ("data_host_cities.json", "w") as f:
    json.dump(data, f, indent=4)